export enum HttpStatusCodesFMS {
  DUPLICATE_ENTRY_FOUND = 251,
  INVALID_DEPARTURE_AND_ARRIVAL_DATE= 253,
  ENTRY_NOT_FOUND = 254,
  VERSION_MISMATCHED = 257,
  CANNOT_BE_EXECUTED = 259,
  ROUTE_DOESNT_EXIST = 258
}
