###
POST http://localhost:8080/flights/add-flight
Content-Type: application/json

{
  "id": "12",
  "flight_number": "123",
  "departure": "Colombo",
  "arrival": "sd",
  "departure_date": "2023-04-29",
  "arrival_date": "2023-04-20",
  "departure_time": "13:00",
  "arrival_time": "13:00"
}

###
PUT http://localhost:8080/flights/edit-flight
Content-Type: application/json

{
  "id": "1",
  "flight_number": "1",
  "departure": "Colombo",
  "arrival": "Colombo",
  "departure_date": "2023-04-26",
  "arrival_date": "2023-04-27",
  "departure_time": "13:00",
  "arrival_time": "13:00"
}

###
DELETE http://localhost:8080/flights/delete-flight?id=12
Accept: application/json

###
GET http://localhost:8080/flights/get-flights
