###
POST http://localhost:8080/flights/add-flight
Content-Type: application/json

{
  "flightId": "ldibdve-uxbom5",
  "flightNumber": "1234",
  "departure": "Colombo",
  "arrival": "",
  "departureDate": "2023-04-29",
  "arrivalDate": "2023-04-30",
  "departureTime": "13:00",
  "arrivalTime": "13:00"
}

###
PUT http://localhost:8080/flights/edit-flight
Content-Type: application/json

{
  "flightId": "12s",
  "flightNumber": "1234",
  "departure": "Colombo",
  "arrival": "Dubai",
  "departureDate": "2024-02-24",
  "arrivalDate": "2025-04-30",
  "departureTime": "23:42",
  "arrivalTime": "13:00"
}

###
DELETE http://localhost:8080/flights/delete-flight?id=12s
Accept: application/json

###
GET http://localhost:8080/flights/get-flights


###
GET http://localhost:8080/flights/get-airports


###
GET http://localhost:8080/flights/get-filtered-flights?flightNumber=&departure=&arrival=&departureDate=&departureTime=&arrivalDate=&arrivalTime=