GET http://localhost:8080/api/fares/locations
###
GET http://localhost:8080/api/fares/search
###
GET http://localhost:8080/api/fares/search?departure=colombo
###
GET http://localhost:8080/api/fares/search?arrival=dubai
###
GET http://localhost:8080/api/fares/search?departure=colombo&arrival=sydney
###
GET http://localhost:8080/api/fares/search?departure=madrid
###
POST http://localhost:8080/api/fares/fare
Content-Type: application/json

{ "departure": "dubai", "arrival": "kandy", "fare": 195 }
###
PUT http://localhost:8080/api/fares/fare
Content-Type: application/json

{ "id": 1, "departure": "colombo", "arrival": "dubai", "fare": 70 }
###
DELETE http://localhost:8080/api/fares/fare?id=3
###
GET http://localhost:8080/api/availability
Content-Type: application/json

{ "departure": "dubai", "arrival": "kandy" }